### ISSUE TITLE
No updation of data copied in the clipboard

### ISSUE THREAD

**Issue by dibyadas** [nikhilkumarsingh/clix#4]
Currently, if the clipboard gui is open, and one copies some text, it is not updated in the gui. Only when the current gui is closed and another one is opened , the new data is shown.

**Comment by nikhilkumarsingh** [comment]
It requires dynamic updation of tkinter GUI. All frames need to be shifted. You can try this task as well.

**Comment by dibyadas** [comment]
Can this have a bounty?  I mean this seems like a good enhancement feature.

**Comment by dibyadas** [comment]
@nikhilkumarsingh What about the bounty thing? I think I may have a good idea on how to implement this.

**Comment by nikhilkumarsingh** [comment]
@championswimmer
This task can be awarded 1000 bounty points. 
Please assign points against this issue.

**Comment by dibyadas** [comment]
@nikhilkumarsingh Ok. So this was harder than I thought. Although I have a working version now, its not exactly what I wanted to. I have made the clipboard and the keyboard hook part, asynchronous. So now even if the clipboard is showing, text copied now will be processed and displayed in the shell. And whenever text is copied, the clipboard is closed and new one is opened with the updated data. 
While I wanted the data to be updated live, it will require and change in the structure of the program. In my opinion, this becomes an overkill (Unless, ofcourse, a simple alternative is found) . 
What's your opinion?
Also, the bounty has not yet been added. I have put in quite some effort in this. And would love if it's reflected here.
Thanks,
Dibya Prakash Das
