### ISSUE TITLE
clix update

### ISSUE THREAD

**Issue by umangahuja1** [nikhilkumarsingh/clix#8]
From readme
`Remove the . prefix from .pyxhook and .gui for the following imports in clix.py`

If this is the edit required in clic.py, why not update directly in main repo

**Comment by nikhilkumarsingh** [comment]
If you're running clix as a package, you need the '.' prefix on relative imports.
But if you want to use it like a simple python script (say you wanna run `clix.py`) then, '.' prefix is not required and it raises an error.

**Comment by umangahuja1** [comment]
Oh ok thanks. I think then you can close this down.
